### ISSUE TITLE
TypeError: dropout(): argument 'input' (position 1) must be Tensor, not str

### ISSUE THREAD

**Issue by azizcu** [NadirEM/nlp-notebooks#1]
Error in train_loader  
Fine_tune_ALBERT_sentence_pair_classification

0%|          | 0/86 [00:00<?, ?it/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-95-f9509d78ee25> in <module>()
     29 lr_scheduler = get_linear_schedule_with_warmup(optimizer=opti, num_warmup_steps=num_warmup_steps, num_training_steps=t_total)
     30 
---> 31 train_bert(net, criterion, opti, lr, lr_scheduler, train_loader, val_loader, epochs, iters_to_accumulate)

6 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in dropout(input, p, training, inplace)
    981     return (_VF.dropout_(input, p, training)
    982             if inplace
--> 983             else _VF.dropout(input, p, training))
    984 
    985 

TypeError: dropout(): argument 'input' (position 1) must be Tensor, not str

**Comment by AlsalehAbdullah** [comment]
Hi,

I have the same issue! I'm using AraBERT instead of ALBERT. I also commented on the "for loop" in class SentencePairClassifier for hidden size, so I made hidden size variable that equals to 768.

Below are the output of the error


Reading training data...
Reading validation data...

  0%|          | 0/209 [00:00<?, ?it/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-47-1c613f141340> in <module>()
     28 lr_scheduler = get_linear_schedule_with_warmup(optimizer=opti, num_warmup_steps=num_warmup_steps, num_training_steps=t_total)
     29 
---> 30 train_bert(net, criterion, opti, lr, lr_scheduler, train_loader, val_loader, epochs, iters_to_accumulate)

6 frames
<ipython-input-43-f4519f6e9fdf> in train_bert(net, criterion, opti, lr, lr_scheduler, train_loader, val_loader, epochs, iters_to_accumulate)
     23             with autocast():
     24                 # Obtaining the logits from the model
---> 25                 logits = net(seq, attn_masks, token_type_ids)
     26 
     27                 # Computing loss

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

/usr/local/lib/python3.6/dist-packages/torch/cuda/amp/autocast_mode.py in decorate_autocast(*args, **kwargs)
    133         def decorate_autocast(*args, **kwargs):
    134             with self:
--> 135                 return func(*args, **kwargs)
    136         return decorate_autocast
    137 

<ipython-input-41-c1fc498a4989> in forward(self, input_ids, attn_masks, token_type_ids)
     44         # Linear Layer and a Tanh activation. The Linear layer weights were trained from the sentence order prediction (ALBERT) or next sentence prediction (BERT)
     45         # objective during pre-training.
---> 46         logits = self.cls_layer(self.dropout(pooler_output))
     47 
     48         return logits

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/dropout.py in forward(self, input)
     56 
     57     def forward(self, input: Tensor) -> Tensor:
---> 58         return F.dropout(input, self.p, self.training, self.inplace)
     59 
     60 

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in dropout(input, p, training, inplace)
    981     return (_VF.dropout_(input, p, training)
    982             if inplace
--> 983             else _VF.dropout(input, p, training))
    984 
    985 

TypeError: dropout(): argument 'input' (position 1) must be Tensor, not str

**Comment by NadirEM** [comment]
Hello,
I made a quick fix by adding the versions of the two libraries (transformers and datasets) I was using in September.
It should work now.

**Comment by azizcu** [comment]
Hi NadirEM, 
Ok. 
Another question is can i use it for sentence pair regression?
 if possible please explain it how(with example) ?

**Comment by NadirEM** [comment]
Hi @azizcu, it is already fixed.
Please, if you have an unrelated problem/question, try to open another issue next time.
For sequence-pair regression, you can use torch.nn.MSELoss instead of torch.nn.BCEWithLogitsLoss.
